name: CI

on:
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # trigger on push or pull request to main
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ github.sha }}
          path: dist

  # typecheck:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - run: npm install
  #     - run: npm run typecheck

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - run: npm install
  #     - run: npm run lint

  # verify:
  #   runs-on: ubuntu-latest
  #   needs: [typecheck, lint]
  #   steps:
  #     - run: echo "All checks passed"

  deploy:
    # if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - uses: actions/download-artifact@v3
        with:
          name: dist-${{ github.sha }}
      - name: Deploy
        # uses: JamesIves/github-pages-deploy-action@v4
        # with:
        #   # The branch the action should deploy to
        #   branch: gh-pages
        #   # The folder the action should deploy
        #   folder: dist
        run: |
          echo "looking.."
          ls
