name: CI

on:
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # trigger on push or pull request to main
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - run: npm run typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - run: npm run lint

  verify:
    runs-on: ubuntu-latest
    needs: [typecheck, lint]
    steps:
      - run: echo "All checks passed"

  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: [build, verify]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - name: Deploy
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
        # uses: JamesIves/github-pages-deploy-action@4.1.1
        # with:
        #   # The branch the action should deploy to
        #   branch: gh-pages
        #   # The folder the action should deploy
        #   folder: dist
